In [1]:
import pandas as pd

# Load your combined file
df = pd.read_csv('/content/Merged_Soil_Data.csv')

# Quick look
df.head()

,Unnamed: 0,DISTRICT,BLOCK,PANCHAYAT,VILLAGE,LATITUDE,LONGITUDE,PH,P,K,CA,MG
0,0,Kottayam,Pampady,Akalakunnam,Akalakunnam,9.65674,76.63473,4.5,183.97,372.96,313.9,205.45
1,1,Kottayam,Pampady,Akalakunnam,Akalakunnam,9.65622,76.63101,5.6,57.31,268.24,1000.0,200.65
2,2,Kottayam,Pampady,Akalakunnam,Akalakunnam,9.65564,76.63068,5.9,79.07,565.26,949.95,254.48
3,3,Kottayam,Pampady,Akalakunnam,Akalakunnam,9.65670,76.63118,6.1,68.33,440.72,1000.0,404.48
4,4,Kottayam,Pampady,Akalakunnam,Akalakunnam,9.65708,76.63483,5.8,153.46,227.70,614.2,257.68

In [2]:
# Verify shape and summary
print("Cleaned data shape:", df.shape)
print("\nSummary statistics:\n", df[['P', 'K', 'CA', 'MG', 'PH']].describe())

Cleaned data shape: (3395, 12)

Summary statistics:
                  P            K           MG           PH
count  3395.000000  3395.000000  3395.000000  3395.000000
mean     55.115389   371.905928   194.868006     5.707246
std      48.502590   218.507048   128.033999     0.792423
min       1.300000    16.020000     0.300000     0.200000
25%      19.290000   223.495000   102.500000     5.200000
50%      38.840000   327.260000   173.830000     5.700000
75%      75.820000   468.380000   275.000000     6.235000
max     305.400000  1200.000000   500.000000     8.000000

In [3]:
# Check how many missing values each column has
df.isnull().sum()

Unnamed: 0    0
DISTRICT      0
BLOCK         0
PANCHAYAT     0
VILLAGE       0
LATITUDE      0
LONGITUDE     0
PH            0
P             0
K             0
CA            0
MG            0
dtype: int64

# removes unrealistic nutrient readings that are too far from the typical range.

In [4]:
import numpy as np

def remove_outliers_iqr(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    return data[(data[column] >= lower) & (data[column] <= upper)]

# Convert nutrient columns to numeric, coercing errors
for col in ['P', 'K', 'CA', 'MG', 'PH']:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Drop rows with NaN values introduced by coercion
df.dropna(subset=['P', 'K', 'CA', 'MG', 'PH'], inplace=True)

# Apply to nutrient columns
for col in ['P', 'K', 'CA', 'MG', 'PH']:
    df = remove_outliers_iqr(df, col)

# Check Cleaned Data

In [5]:
# Verify shape and summary
print("Cleaned data shape:", df.shape)
print("\nSummary statistics:\n", df[['P', 'K', 'CA', 'MG', 'PH']].describe())

Cleaned data shape: (3018, 12)

Summary statistics:
                  P            K           CA           MG           PH
count  3018.000000  3018.000000  3018.000000  3018.000000  3018.000000
mean     47.675852   334.865292   489.985636   191.223602     5.672293
std      38.500939   162.591100   336.213824   126.294643     0.754125
min       1.300000    16.020000     1.520000     0.300000     3.500000
25%      17.930000   217.280000   196.862500   100.590000     5.120000
50%      35.840000   315.225000   430.575000   170.795000     5.700000
75%      65.482500   436.350000   764.262500   270.775000     6.200000
max     160.630000   824.210000  1578.200000   500.000000     7.760000

In [6]:
output_path = '/content/Cleaned_Soil_Data.csv'
df.to_csv(output_path, index=False)
print("✅ Cleaned dataset saved at:", output_path)

✅ Cleaned dataset saved at: /content/Cleaned_Soil_Data.csv